export let mytours=
[
    {
        place:"Bangalore",
        image:"https://images.pexels.com/photos/739987/pexels-photo-739987.jpeg?auto=compress&cs=tinysrgb&w=600",
        content:`Bangalore (/bæŋɡəˈlɔːr/), officially Bengaluru (Kannada pronunciation: [ˈbeŋgɐɭuːɾu] (listen)), is the capital and largest city of the Indian state of Karnataka. It has a population of more than 8 million and a metropolitan population of around 11 million, making it the third most populous city and fifth most populous urban agglomeration in India, as well as the largest city in South India, and the 27th largest city in the world.[12] Located on the Deccan Plateau, at a height of over 900 m (3,000 ft) above sea level, Bangalore has a pleasant climate throughout the year, with its parks and green spaces earning it the reputation as the "Garden City" of India.[13] Its elevation is the highest among the major cities of India.[14] An aerospace, heavy engineering and electronics hub since the 1960s, Bangalore is widely regarded as the "Silicon Valley of India" because of its role as the nation's leading information technology (IT) exporter.[1][13] In the Ease of Living Index 2020 (published by the Ministry of Housing and Urban Affairs), it was ranked the most livable Indian city with a population of over a million. [15] It also ranks among the highest Indian cities in terms of global livability rankings as well.`
    },
    {
        place:"Mumbai",
        image:"https://images.pexels.com/photos/4055002/pexels-photo-4055002.jpeg?auto=compress&cs=tinysrgb&w=600",
        content:`Bangalore (/bæŋɡəˈlɔːr/), officially Bengaluru (Kannada pronunciation: [ˈbeŋgɐɭuːɾu] (listen)), is the capital and largest city of the Indian state of Karnataka. It has a population of more than 8 million and a metropolitan population of around 11 million, making it the third most populous city and fifth most populous urban agglomeration in India, as well as the largest city in South India, and the 27th largest city in the world.[12] Located on the Deccan Plateau, at a height of over 900 m (3,000 ft) above sea level, Bangalore has a pleasant climate throughout the year, with its parks and green spaces earning it the reputation as the "Garden City" of India.[13] Its elevation is the highest among the major cities of India.[14] An aerospace, heavy engineering and electronics hub since the 1960s, Bangalore is widely regarded as the "Silicon Valley of India" because of its role as the nation's leading information technology (IT) exporter.[1][13] In the Ease of Living Index 2020 (published by the Ministry of Housing and Urban Affairs), it was ranked the most livable Indian city with a population of over a million. [15] It also ranks among the highest Indian cities in terms of global livability rankings as well.`
    },
    {
        place:"Delhi",
        image:"https://images.pexels.com/photos/1007426/pexels-photo-1007426.jpeg?auto=compress&cs=tinysrgb&w=600",
        content:`Bangalore (/bæŋɡəˈlɔːr/), officially Bengaluru (Kannada pronunciation: [ˈbeŋgɐɭuːɾu] (listen)), is the capital and largest city of the Indian state of Karnataka. It has a population of more than 8 million and a metropolitan population of around 11 million, making it the third most populous city and fifth most populous urban agglomeration in India, as well as the largest city in South India, and the 27th largest city in the world.[12] Located on the Deccan Plateau, at a height of over 900 m (3,000 ft) above sea level, Bangalore has a pleasant climate throughout the year, with its parks and green spaces earning it the reputation as the "Garden City" of India.[13] Its elevation is the highest among the major cities of India.[14] An aerospace, heavy engineering and electronics hub since the 1960s, Bangalore is widely regarded as the "Silicon Valley of India" because of its role as the nation's leading information technology (IT) exporter.[1][13] In the Ease of Living Index 2020 (published by the Ministry of Housing and Urban Affairs), it was ranked the most livable Indian city with a population of over a million. [15] It also ranks among the highest Indian cities in terms of global livability rankings as well.`
    },
    {
        place:"Hyderabad",
        image:"https://images.pexels.com/photos/6079192/pexels-photo-6079192.jpeg?auto=compress&cs=tinysrgb&w=600",
        content:`Bangalore (/bæŋɡəˈlɔːr/), officially Bengaluru (Kannada pronunciation: [ˈbeŋgɐɭuːɾu] (listen)), is the capital and largest city of the Indian state of Karnataka. It has a population of more than 8 million and a metropolitan population of around 11 million, making it the third most populous city and fifth most populous urban agglomeration in India, as well as the largest city in South India, and the 27th largest city in the world.[12] Located on the Deccan Plateau, at a height of over 900 m (3,000 ft) above sea level, Bangalore has a pleasant climate throughout the year, with its parks and green spaces earning it the reputation as the "Garden City" of India.[13] Its elevation is the highest among the major cities of India.[14] An aerospace, heavy engineering and electronics hub since the 1960s, Bangalore is widely regarded as the "Silicon Valley of India" because of its role as the nation's leading information technology (IT) exporter.[1][13] In the Ease of Living Index 2020 (published by the Ministry of Housing and Urban Affairs), it was ranked the most livable Indian city with a population of over a million. [15] It also ranks among the highest Indian cities in terms of global livability rankings as well.`
    }
]